<?php

namespace cloud\siteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanEstudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanEstudioRepository extends EntityRepository
{
}
