security:
    encoders:
        cloud\siteBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        user_db:
            entity: { class: cloud\siteBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
#            http_basic:
#                realm: "Introduzca Usuario y Contraseña"
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /redirect
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin/*, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }